dataset_path = "data/sift-128-euclidean.hdf5"
dimension = 128
top_k = 10
warmup_queries = 100
query_limit = 1000
query_cycles = 100
load_index_prefix = "data/index/sift-128-euclidean-1MLN"
seed = 42
ef_searches = [32, 64, 128]
# output_json = "data/results/sift-1m.json"

# base_limit = 100000
# save_index_prefix = "data/index/sift-128-euclidean-1MLN"

# defaults
# base_datasets = ["train", "base"]
# query_datasets = ["test", "query", "queries"]
# ground_truth_datasets = ["neighbors", "knns", "groundtruth"]

# [quantized]
# quantizers = 64
# pq_k = 256
# pq_oracle = false

[[configs]]
m = 16
m0 = 32
ef_construction = 128

[[configs]]
m = 16
m0 = 32
ef_construction = 128

[[configs]]
m = 32
m0 = 64
ef_construction = 200

[[configs]]
m = 32
m0 = 64
ef_construction = 200
